server:
  port: 8080
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    config:
      label: session2
      uri: http://localhost:8888
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: library-service
        uri: lb://library-service
        predicates:
          - Path=/library-service/**
        filters:
          - RewritePath=/library-service/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
#logging:
#  level:
#    root: debug
